---
additional_software: []
custom_command_file: ""
# e.g. trixie or resolute
desired_release: ""
ingress_ports: []

# Debian kernel flavours
kernel_debian_backports: false
kernel_debian_cloud: false

# node metrics
metrics_port: 0
node_metrics: false
prometheus_server_v4: ""
prometheus_server_v6: ""

# Image
is_image: false

# Nginx
nginx_metrics: false
nginx_public_site: false
nginx_site_directories: []

# https://github.com/prometheus/node_exporter
# due to tiny cloud instances reduce the CPU pressure at the source (instead to filter by "params:" at prometheus server)
node_exporter_collectors:
  - arp
  - conntrack
  - cpu
  - diskstats
  - filefd
  - filesystem
  - filesystem.mount-points-exclude="^/(dev|proc|run/credentials/.+|sys)($|/)"
  - loadavg
  - meminfo
  - netdev
  - netstat
  - processes
  - sockstat
  - softnet
  - stat
  - udp_queues
  - uname
  - vmstat

# Snowflake
is_snowflake: false
snowflake_metrics: false

# Tor
ddos_metrics: false
is_tor: false
tor_bridge_distribution: none
tor_metrics: false
tor_shape_egress: false
torutils_path: "https://github.com/toralf/torutils/raw/{{ torutils_git_version | default('main') }}"
