---
- name: Check for a known artefact
  delegate_to: localhost
  throttle: 1
  ansible.builtin.lineinfile:
    line: "{{ item.checksum }}"
    path: "{{ infodir }}/artefact/_known.txt"
  register: __known_artefact

- name: Store all hostnames of an artefact
  delegate_to: localhost
  throttle: 1
  ansible.builtin.lineinfile:
    line: "{{ inventory_hostname }}"
    path: "{{ infodir }}/artefact/_hostname.{{ item.checksum }}.txt"

- name: Work on new artefact
  when: __known_artefact.changed
  vars:
    _fname: "object.{{ item.checksum }}.tar.gz"
  block:
    - name: Archive artefact
      changed_when: false
      ansible.builtin.command:
        cmd: >-
          tar -czpf /tmp/{{ _fname }} {{ item.path }}

    - name: Fetch artefact archive
      throttle: 1
      ansible.builtin.fetch:
        src: "/tmp/{{ _fname }}"
        dest: "{{ infodir }}/artefact/{{ _fname }}"

    - name: Delete tmp artefact archive
      ansible.builtin.file:
        path: "/tmp/{{ _fname }}"
        state: absent

  rescue:
    - name: Reset known state for artefact
      delegate_to: localhost
      throttle: 1
      ansible.builtin.lineinfile:
        line: "{{ item.checksum }}"
        path: "{{ infodir }}/artefact/_known.txt"
        state: absent

  always:
    - name: Get dmesg for artefact
      ansible.builtin.include_tasks: _dmesg.yaml

    - name: Get kernel config for artefact
      ansible.builtin.include_tasks: "{{ role_path }}/../../../playbooks/roles/lib/_kconfig.yaml"
