---
- name: Get dmesg
  changed_when: false
  ansible.builtin.shell:
    cmd: >-
      dmesg |
        {{ filter_sensitive_data }}
  register: __dmesg

- name: File dmesg
  delegate_to: localhost
  throttle: "{{ concurrent_local_jobs }}"
  ansible.builtin.copy:
    dest: "{{ infodir }}/dmesg/{{ inventory_hostname }}.{{ now(utc=true, fmt='%Y-%m-%dT%H:%M:%SZ') }}.txt"
    content: "{{ __dmesg.stdout }}"
