---
- name: Check if firewall is up
  changed_when: _firewall_healthy.rc != 0
  failed_when: false
  ansible.builtin.shell:
    cmd: |-
      set -euf

      iptables  -nvL INPUT | grep -e "/\* .* IPv4 .* \*/"
      ip6tables -nvL INPUT | grep -e "/\* .* IPv6 .* \*/"
      if [[ {{ is_tor | ternary('y', 'n') }} == y ]]; then
        iptables  -nvL INPUT | grep 'match-set torutils-ddos-v4-'
        if [[ {{ (tor_bridge_distribution | length == 0) | ternary('y', 'n') }} == y ]]; then
          ip6tables -nvL INPUT | grep 'match-set torutils-ddos-v6-'
        fi
      fi
      iptables  -nvL INPUT | grep 'add-set torutils-tarpit-v4'
      ip6tables -nvL INPUT | grep 'add-set torutils-tarpit-v6'
    executable: /bin/bash
  register: _firewall_healthy
  notify: Not Healthy

- name: File firewall state
  delegate_to: localhost
  throttle: 1
  vars:
    _file: "{{ (is_tor | default(false)) | ternary('firewall_base_is_down', 'firewall_tor_is_down') }}"
  ansible.builtin.lineinfile:
    line: "{{ inventory_hostname }}"
    path: "{{ infodir }}/{{ _file }}"
    regexp: "^{{ inventory_hostname }}$"
    state: "{{ (_firewall_healthy.rc != 0) | ternary('present', 'absent') }}"
