---
- name: Check if firewall is up
  changed_when: _firewall_healthy.rc != 0
  failed_when: false
  ansible.builtin.shell:
    cmd: |-
      set -euf

      iptables  -nvL INPUT | grep -e "/\* .* IPv4 .* \*/"
      ip6tables -nvL INPUT | grep -e "/\* .* IPv6 .* \*/"
      iptables  -nvL INPUT | grep 'add-set torutils-tarpit-v4'
      ip6tables -nvL INPUT | grep 'add-set torutils-tarpit-v6'
  register: _firewall_healthy
  notify: Not Healthy

- name: File firewall state
  delegate_to: localhost
  throttle: 1
  vars:
    _file: "{{ (tor_port | default(0) == 0) | ternary('firewall_base_is_down', 'firewall_tor_is_down') }}"
  ansible.builtin.lineinfile:
    line: "{{ inventory_hostname }}"
    path: "{{ infodir }}/{{ _file }}"
    regexp: "^{{ inventory_hostname }}$"
    state: "{{ (_firewall_healthy.rc != 0) | ternary('present', 'absent') }}"
