---
- name: Grep system log for issue/s
  changed_when: false
  failed_when: _result_syslog.stderr | length > 0
  ansible.builtin.shell:
    cmd: |-
      journalctl {{ (issue_since | length > 0) | ternary('--since "' + issue_since + '"', '-b') }} --quiet |
        grep -v -F 'Speculative Return Stack Overflow: WARNING:' |
        grep -m 500 -F \
          -e 'BUG:' \
          -e 'BUG at' \
          -e 'Call Trace:' \
          -e 'Error:' \
          -e 'invoked oom-killer' \
          -e 'No space left on device' \
          -e 'Oops:' \
          -e 'rebooting.' \
          -e '.service: Control process exited' \
          -e 'status=9/KILL' \
          -e 'WARNING:'
  register: _result_syslog

- name: File issue
  delegate_to: localhost
  throttle: 1
  ansible.builtin.blockinfile:
    block: "{{ _result_syslog.stdout }}"
    path: "{{ infodir }}/issue.txt"
    marker: "# {mark} {{ inventory_hostname }} "
    state: "{{ (_result_syslog.stdout | length > 0) | ternary('present', 'absent') }}"
