---
- name: Install/Update tools for DDoS
  ansible.builtin.apt:
    name:
      - ipset
      - jq

#
# ingress
#
- name: Get DDoS scripts
  throttle: 8
  retries: 1
  ansible.builtin.get_url:
    url: "{{ torutils_path }}/{{ item }}"
    dest: /root/
  loop:
    - ipv4-rules.sh
    - ipv6-rules.sh
  register: _ddos_script

- name: Basic test that DDoS works
  when: _ddos_script.changed
  changed_when: false
  ansible.builtin.shell:
    cmd: |-
      set -euf

      /root/ipv4-rules.sh
      /root/ipv6-rules.sh

- name: DDoS
  vars:
    _additional_ports_v4: "{{ [ansible_facts.default_ipv4.address] | product(additional_ports) | map('join', ':') }}"
    _additional_ports_v6: "{{ ['[' + ansible_facts.default_ipv6.address + ']'] | product(additional_ports) | map('join', ':') }}"
    _add_local_services_v4: >-
      {{ (_additional_ports_v4 | length > 0) | ternary('ADD_LOCAL_SERVICES="' + _additional_ports_v4 | join(' ') + '"', '') }}
    _add_local_services_v6: >-
      {{ (_additional_ports_v6 | length > 0) | ternary('ADD_LOCAL_SERVICES6="' + _additional_ports_v6 | join(' ') + '"', '') }}
    # Prometheus server
    _add_remote_services_v4: >-
      {{ (metrics_port > 0 and prometheus_server | length > 0) |
        ternary('ADD_REMOTE_SERVICES="' + prometheus_server + '>' + metrics_port | string + '"', '') }}
    _add_remote_services_v6: >-
      {{ (metrics_port > 0 and prometheus_server6 | length > 0 ) |
        ternary('ADD_REMOTE_SERVICES6="[' + prometheus_server6 + ']>' + metrics_port | string + '"', '') }}
    # ipv4 for all
    _configured_relays_v4: >-
      {{ 'CONFIGURED_RELAYS="' + ansible_facts.default_ipv4.address + ':' + tor_port | string + '"' }}
    # no ipv6 for bridges
    _configured_relays_v6: >-
      {{ (tor_bridge_distribution | length == 0) |
        ternary('CONFIGURED_RELAYS6="[' + ansible_facts.default_ipv6.address + ']:' + tor_port | string + '"', '') }}
  block:
    - name: Create DDoS cron job for reboot
      ansible.builtin.cron:
        name: start firewall
        special_time: reboot
        job: >-
          {{ _add_local_services_v4 }} {{ _add_remote_services_v4 }} {{ _configured_relays_v4 }} /root/ipv4-rules.sh start;
          {{ _add_local_services_v6 }} {{ _add_remote_services_v6 }} {{ _configured_relays_v6 }} /root/ipv6-rules.sh start
      register: _ddos_cron

    - name: Check if DDoS is in place
      failed_when: _ddos_in_place.rc not in (0, 1)
      changed_when: false
      ansible.builtin.shell:
        cmd: |-
          set -euf

          iptables  -nvL INPUT | grep -F '/* DDoS IPv4'
          ip6tables -nvL INPUT | grep -F '/* DDoS IPv6'
          iptables  -nvL INPUT | grep 'match-set .* src'
          ip6tables -nvL INPUT | grep 'match-set .* src'
      register: _ddos_in_place

    - name: Ensure that DDoS is up
      changed_when: true
      when: _ddos_script.changed or _ddos_cron.changed or _ddos_in_place.rc == 1
      ansible.builtin.shell:
        cmd: |-
          set -euf

          /root/ipv4-rules.sh save
          /root/ipv6-rules.sh save

          {{ _add_local_services_v4 }} {{ _add_remote_services_v4 }} {{ _configured_relays_v4 }} /root/ipv4-rules.sh start
          {{ _add_local_services_v6 }} {{ _add_remote_services_v6 }} {{ _configured_relays_v6 }} /root/ipv6-rules.sh start

- name: Remove iptables-persistent
  ansible.builtin.apt:
    name:
      - iptables-persistent
    state: absent

- name: Remove iptables state after DDoS setup
  ansible.builtin.file:
    path: "/etc/iptables/rules.{{ item }}"
    state: absent
  loop:
    - v4
    - v6

- name: Create DDoS cron job to save ipsets
  ansible.builtin.cron:
    name: save ipset
    special_time: hourly
    job: /root/ipv4-rules.sh save; /root/ipv6-rules.sh save

- name: Create DDoS cron job to update Tor authority ip addresses
  ansible.builtin.cron:
    name: Tor authority ip addresses update
    special_time: daily
    job: /root/ipv4-rules.sh update; /root/ipv6-rules.sh update

#
# egress
#
- name: Get egress firewall script
  when: tor_shape_egress
  throttle: 16
  retries: 1
  ansible.builtin.get_url:
    url: "{{ torutils_path }}/ipv4-rules-egress.sh"
    dest: /root/
  register: _egress_script

- name: Ensure egress is updated
  changed_when: true
  when: _egress_script.changed
  ansible.builtin.shell: # noqa command-instead-of-shell
    cmd: |-
      /root/ipv4-rules-egress.sh {{ tor_shape_egress | ternary('start', '') }}

- name: Handle egress firewall cron job
  ansible.builtin.cron:
    name: start firewall egress
    special_time: reboot
    job: >-
      /root/ipv4-rules-egress.sh start
    state: "{{ tor_shape_egress | ternary('present', 'absent') }}"
