---
- name: Install/Update Firewall tools
  ansible.builtin.apt:
    name:
      - jq
      - nftables

- name: Create/Update nftables config
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
  notify: Reload nftables

- name: Check nftables config
  changed_when: false
  ansible.builtin.command:
    cmd: |-
      nft -c -f /etc/nftables.conf

# Configure nftables persistence under /var like Gentoo

- name: Ensure target directory exists to save nftables
  ansible.builtin.file:
    path: /var/lib/nftables
    state: directory
    mode: "0750"

- name: Create override directory for nftables.service
  ansible.builtin.file:
    path: /etc/systemd/system/nftables.service.d
    state: directory
    mode: "0755"

- name: Add nftables systemd override
  ansible.builtin.copy:
    src: nftables.override.conf
    dest: /etc/systemd/system/nftables.service.d/override.conf
  notify: Reload systemd

- name: Enable/Start nftables
  ansible.builtin.systemd_service:
    name: nftables
    state: started
    enabled: true
    daemon_reload: true

# the filesystem is read-only when nftables starts
- name: Create cron job to delete saved nftables after reboot
  ansible.builtin.cron:
    name: delete saved nftables
    special_time: reboot
    job: >-
      rm -f /var/lib/nftables/rules-save
