---
- name: Sysctl values for base firewall
  vars:
    _max: "{{ (ansible_facts.memtotal_mb < 1024) | ternary((2**18) | int, (2**19) | int) }}"
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/21firewall.conf
    sysctl_set: true
  loop:
    - name: net.core.somaxconn
      value: "{{ _max }}"
    - name: net.ipv4.tcp_max_syn_backlog
      value: "{{ _max }}"

- name: Create base firewall script
  ansible.builtin.template:
    src: "firewall-ip{{ item }}.sh.j2"
    dest: "/root/firewall-ip{{ item }}.sh"
    mode: "0700"
  loop:
    - v4
    - v6
  register: _firewall_base_script

- name: Check if base firewall is up
  changed_when: _firewall_base_is_up.rc != 0
  failed_when: false
  ansible.builtin.shell:
    cmd: |-
      set -euf

      iptables  -nvL INPUT | grep -e "/\* .* IPv4 .* \*/"
      ip6tables -nvL INPUT | grep -e "/\* .* IPv6 .* \*/"
      iptables  -nvL INPUT | grep 'add-set torutils-tarpit-v4'
      ip6tables -nvL INPUT | grep 'add-set torutils-tarpit-v6'
  register: _firewall_base_is_up

- name: Start base firewall
  when: _firewall_base_script.changed or _firewall_base_is_up.changed
  changed_when: true
  ansible.builtin.command:
    cmd: >-
      /root/firewall-ip{{ item }}.sh start
  loop:
    - v4
    - v6

- name: Create Firewall base cron job for reboot
  ansible.builtin.cron:
    # "name" must be the same as for DDoS
    name: start firewall
    special_time: reboot
    job: >-
      /root/firewall-ipv4.sh start;
      /root/firewall-ipv6.sh start
  register: _ddos_cron
