---
- name: Install/Update tools for DDoS
  ansible.builtin.apt:
    name:
      - jq

#
# ingress
#
- name: Get DDoS scripts
  throttle: 8
  retries: 1
  ansible.builtin.get_url:
    url: "{{ torutils_path }}/{{ item }}"
    dest: /root/
  loop:
    - ipv4-rules.sh
    - ipv6-rules.sh
  register: _ddos_script

- name: Basic test that DDoS works
  when: _ddos_script.changed
  changed_when: false
  ansible.builtin.shell:
    cmd: |-
      set -euf

      /root/ipv4-rules.sh
      /root/ipv6-rules.sh

# use CONFIGURED_RELAYS[6] here b/c torrc might not yet been configured at initial setup
- name: DDoS
  vars:
    _ingress_ports_v4: "{{ [ansible_facts.default_ipv4.address] | product(ingress_ports) | map('join', ':') }}"
    _ingress_ports_v6: "{{ ['[' + ansible_facts.default_ipv6.address + ']'] | product(ingress_ports) | map('join', ':') }}"
    _local_v4: >-
      {{ (_ingress_ports_v4 | length > 0) | ternary('TORUTILS_LOCAL_SERVICES_V4="' + _ingress_ports_v4 | join(' ') + '"', '') }}
    _local_v6: >-
      {{ (_ingress_ports_v6 | length > 0) | ternary('TORUTILS_LOCAL_SERVICES_V6="' + _ingress_ports_v6 | join(' ') + '"', '') }}
    # Prometheus server
    _remote_v4: >-
      {{ (metrics_port > 0 and prometheus_server_v4 | length > 0) |
        ternary('TORUTILS_REMOTE_SERVICES_V4="' + prometheus_server_v4 + '>' + metrics_port | string + '"', '') }}
    _remote_v6: >-
      {{ (metrics_port > 0 and prometheus_server_v6 | length > 0 ) |
        ternary('TORUTILS_REMOTE_SERVICES_V6="[' + prometheus_server_v6 + ']>' + metrics_port | string + '"', '') }}
    # ipv4 for all
    _relays_v4: >-
      {{ 'TORUTILS_RELAYS_V4="' + ansible_facts.default_ipv4.address + ':' + tor_port | string + '"' }}
    # no ipv6 for bridges
    _relays_v6: >-
      {{ (tor_bridge_distribution | length == 0) |
        ternary('TORUTILS_RELAYS_V6="[' + ansible_facts.default_ipv6.address + ']:' + tor_port | string + '"', '') }}
    # DDoS overflow
    _netmask_v4: "" # "TORUTILS_NETMASK_V4=27"
    _netmask_v6: "" # "TORUTILS_NETMASK_V6=59"
    _args_v4: "{{ _local_v4 }} {{ _remote_v4 }} {{ _relays_v4 }} {{ _netmask_v4 }}"
    _args_v6: "{{ _local_v6 }} {{ _remote_v6 }} {{ _relays_v6 }} {{ _netmask_v6 }}"
  block:
    - name: Create DDoS cron job for reboot
      ansible.builtin.cron:
        # "name" must be the same as for base firewall
        name: start firewall
        special_time: reboot
        job: >-
          {{ _args_v4 }} /root/ipv4-rules.sh start;
          {{ _args_v6 }} /root/ipv6-rules.sh start
      register: _ddos_cron

    - name: Check if DDoS is in place
      failed_when: _ddos_in_place.rc not in (0, 1)
      changed_when: false
      ansible.builtin.shell:
        cmd: |-
          set -euf

          iptables  -nvL INPUT | grep -F '/* DDoS IPv4'
          ip6tables -nvL INPUT | grep -F '/* DDoS IPv6'
          iptables  -nvL INPUT | grep 'match-set torutils-ddos-v4-'
          if [[ {{ (tor_bridge_distribution | length == 0) | ternary('y', 'n') }} == y ]]; then
            ip6tables -nvL INPUT | grep 'match-set torutils-ddos-v6-'
          fi
          iptables  -nvL INPUT | grep 'add-set torutils-tarpit-v4'
          ip6tables -nvL INPUT | grep 'add-set torutils-tarpit-v6'
      register: _ddos_in_place

    - name: Ensure that DDoS is up
      changed_when: true
      when: _ddos_script.changed or _ddos_cron.changed or _ddos_in_place.rc != 0
      ansible.builtin.shell:
        cmd: |-
          set -euf

          {{ _args_v4 }} /root/ipv4-rules.sh start
          {{ _args_v6 }} /root/ipv6-rules.sh start

#
# egress
#
- name: Get egress firewall script
  when: tor_shape_egress
  throttle: 16
  retries: 1
  ansible.builtin.get_url:
    url: "{{ torutils_path }}/ipv4-rules-egress.sh"
    dest: /root/
  register: _egress_script

- name: Ensure egress is updated
  changed_when: true
  when: _egress_script.changed
  ansible.builtin.shell: # noqa command-instead-of-shell
    cmd: |-
      /root/ipv4-rules-egress.sh {{ tor_shape_egress | ternary('start', '') }}

- name: Create egress firewall cron job
  ansible.builtin.cron:
    name: start firewall egress
    special_time: reboot
    job: >-
      /root/ipv4-rules-egress.sh start
    state: "{{ tor_shape_egress | ternary('present', 'absent') }}"
