---
- name: Install/Update Firewall tools
  ansible.builtin.apt:
    name:
      - jq
      - nftables

- name: Create/Update nftables config
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
  register: _new_nftables

- name: Check nftables config
  changed_when: false
  ansible.builtin.command:
    cmd: |-
      nft -c -f /etc/nftables.conf

- name: Load new nftables config
  changed_when: true
  when: _new_nftables.changed
  ansible.builtin.command:
    cmd: |-
      nft -o -f /etc/nftables.conf

# Configure nftables persistence under /var like Gentoo

- name: Ensure target directory exists for nft save
  ansible.builtin.file:
    path: /var/lib/nftables
    state: directory
    mode: "0750"

- name: Create override directory for nftables.service
  ansible.builtin.file:
    path: /etc/systemd/system/nftables.service.d
    state: directory
    mode: "0755"

- name: Add nftables systemd override
  ansible.builtin.copy:
    src: nftables.override.conf
    dest: /etc/systemd/system/nftables.service.d/override.conf
  notify: Reload systemd
