---
- name: Install/Update Firewall tools
  ansible.builtin.apt:
    name:
      - jq
      - nftables
  notify: Reload nftables

- name: Enable nft service
  ansible.builtin.systemd_service:
    name: nftables
    state: started
    enabled: true

- name: Create ruleset
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    mode: "0700"
  notify: Reload nftables

- name: Check ruleset
  changed_when: false
  ansible.builtin.command:
    cmd: |-
      nft -c -f /etc/nftables.conf

- name: Create nginx metrics-firewall
  when: firewall_metrics
  ansible.builtin.file:
    path: /var/www/metrics-firewall
    state: directory
    group: www-data
    mode: "0750"

- name: Get metrics firewall
  throttle: 16
  retries: 1
  ansible.builtin.get_url:
    url: "{{ torutils_path }}/metrics-firewall.sh"
    dest: /root/
  notify: Restart metrics firewall

- name: Cron job for metrics firewall
  ansible.builtin.cron:
    name: Firewall metrics
    special_time: reboot
    job: >-
      nice /root/metrics-firewall.sh 15 /var/www/metrics-firewall/nftables.prom
    state: "{{ firewall_metrics | ternary('present', 'absent') }}"
  notify: Restart metrics firewall

- name: Ensure that metrics firewall is running
  changed_when: _metrics_firewall_status.rc != 0
  failed_when: false
  ansible.builtin.shell:
    cmd: |-
      kill -0 $(cat /tmp/metrics-firewall.sh.lock)
  register: _metrics_firewall_status
  notify: Restart metrics firewall

#
# kick away iptables artefacts
#

- name: Stop iptables base firewall
  changed_when: false
  failed_when: false
  ansible.builtin.shell:
    cmd: |-
      for ipt in iptables ip6tables; do
        for chain in INPUT OUTPUT; do
          $ipt -P $chain ACCEPT
          $ipt -F $chain
          $ipt -Z $chain
        done
      done

- name: Disable service tor-relay-ipset
  failed_when: false
  ansible.builtin.systemd_service:
    name: tor-relay-ipset
    state: stopped
    enabled: false
    daemon_reload: true

- name: Remove Firewall base cron job for reboot
  ansible.builtin.cron:
    name: start firewall
    state: absent

- name: Remove old scripts
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/systemd/system/tor-relay-ipset.service
    - /root/firewall-ipv4.sh
    - /root/firewall-ipv6.sh
    - /root/metrics.sh

- name: De-Install iptables
  ansible.builtin.apt:
    name:
      - iptables
    state: absent

- name: Ensure that DDoS metrics is not running
  changed_when: false
  failed_when: false
  ansible.builtin.command:
    cmd: |-
      pkill -9 -f "metrics.sh"

- name: Remove cron job for DDoS metrics firewall
  ansible.builtin.cron:
    name: DDoS metrics
    state: absent

- name: Remove nginx metrics-ddos
  ansible.builtin.file:
    path: /var/www/metrics-ddos/
    state: absent
