---
- name: Gather facts - IPv6
  ansible.builtin.setup:
    gather_subset:
      - all_ipv6_addresses

- name: Ensure IPv6 address has valid prefix
  ansible.builtin.assert:
    quiet: true
    that:
      - "ansible_facts.default_ipv6.address | length > 0"
      - "ansible_facts.default_ipv6.address is not match('fe80::')"

- name: IPv6
  when: ansible_facts.default_ipv6.address != _ipv6_new
  vars:
    _a: "{{ '%x' % (range(0, 65535) |
      random(seed=seed_address + seed_host + 'A' + _ipv6_network)) }}"
    _b: "{{ '%x' % (range(0, 65535) |
      random(seed=seed_address + seed_host + 'B' + _ipv6_network)) }}"
    _c: "{{ '%x' % (range(0, 65535) |
      random(seed=seed_address + seed_host + 'C' + _ipv6_network)) }}"
    _d: "{{ '%x' % (range(0, 65535) |
      random(seed=seed_address + seed_host + 'D' + _ipv6_network)) }}"
    _ipv6_network: "{{ (ansible_facts.default_ipv6.address | split(':'))[:4] | join(':') }}"
    _ipv6_new: "{{ _ipv6_network }}:{{ _a }}:{{ _b }}:{{ _c }}:{{ _d }}"
  block:
    - name: IPv6 change
      changed_when: true
      ansible.builtin.debug:
        msg: "{{ ansible_facts.default_ipv6.address }}  ->  {{ _ipv6_new }}"

    - name: Debian
      when: ansible_facts.distribution == 'Debian'
      block:
        - name: Change IPv6 for Debian
          ansible.builtin.lineinfile:
            line: "    address {{ _ipv6_new }}/64"
            path: /etc/network/interfaces.d/50-cloud-init
            regexp: "^    address "

        - name: Activate new IPv6 address for Debian
          ansible.builtin.systemd_service:
            name: networking
            state: restarted

    - name: Ubuntu
      when: ansible_facts.distribution == 'Ubuntu'
      vars:
        _netplan_path: /etc/netplan/50-cloud-init.yaml
      block:
        - name: Slurp netplan
          ansible.builtin.slurp:
            src: "{{ _netplan_path }}"
          register: netplan_file

        - name: Change netplan
          vars:
            _netplan_data_in: "{{ netplan_file.content | b64decode | from_yaml }}"
            _netplan_data_out: >-
              {{
                _netplan_data_in | combine({
                  'network': {
                    'ethernets': {
                      'eth0': {
                        'addresses': [ _ipv6_new + "/64" ]
                      }
                    }
                  }
                }, recursive=True)
              }}
          ansible.builtin.copy:
            content: "{{ _netplan_data_out | to_nice_yaml(indent=2) }}"
            dest: "{{ _netplan_path }}"
            mode: "0600"

        - name: Disble network config
          ansible.builtin.copy:
            content: |-
              network: {config: disabled}
            dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg

        - name: Apply netplan
          changed_when: true
          ansible.builtin.command:
            cmd: |-
              netplan apply

    - name: Wait till IPv6 works
      changed_when: false
      ansible.builtin.shell:
        cmd: |-
          set -e

          while ip -6 a | grep -q ' tentative'; do
            sleep 1
          done
          ping6 -c 3 {{ _ipv6_new }}
      register: _confirmed

    - name: Gather facts - IPv6 again
      ansible.builtin.setup:
        gather_subset:
          - all_ipv6_addresses
