---
- name: Check for reboot-required file
  changed_when: _reboot_required.stat.exists
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: _reboot_required
  notify: Reboot

- name: Check if a reboot is needed by a kernel
  changed_when: _kernel_reboot_needed.stdout | length > 0
  environment:
    LC_ALL: C.UTF-8
  ansible.builtin.shell:
    cmd: |-
      if needrestart -r l -b | grep -e 'NEEDRESTART-KSTA: 2' -e 'NEEDRESTART-KSTA: 3'; then
        : # yep
      fi
  register: _kernel_reboot_needed
  notify: Reboot

- name: Flush handlers (Reboot)
  ansible.builtin.meta: flush_handlers
