---
- name: Targets
  module_defaults:
    ansible.builtin.lineinfile:
      create: true
      firstmatch: true
      mode: "0644"
      line: '- targets: ["{{ inventory_hostname }}:{{ metrics_port }}"]'
      regexp: '^- targets: \["{{ inventory_hostname }}:'
  block:
    - name: DDoS targets
      delegate_to: localhost
      throttle: 1
      ansible.builtin.lineinfile:
        path: "{{ infodir }}/targets_tor-ddos.yaml"
        state: "{{ ddos_metrics | ternary('present', 'absent') }}"

    - name: Node targets
      delegate_to: localhost
      throttle: 1
      ansible.builtin.lineinfile:
        path: "{{ infodir }}/targets_node.yaml"
        state: "{{ node_metrics | ternary('present', 'absent') }}"

    - name: Snowflake targets
      delegate_to: localhost
      throttle: 1
      when: is_snowflake
      ansible.builtin.lineinfile:
        path: "{{ infodir }}/targets_snowflake.yaml"
        state: "{{ snowflake_metrics | ternary('present', 'absent') }}"

    - name: Tor bridge targets
      delegate_to: localhost
      throttle: 1
      ansible.builtin.lineinfile:
        path: "{{ infodir }}/targets_tor-bridge.yaml"
        state: "{{ (tor_metrics and tor_bridge_distribution | length > 0) |
          ternary('present', 'absent') }}"

    - name: Tor relay targets
      delegate_to: localhost
      throttle: 1
      ansible.builtin.lineinfile:
        path: "{{ infodir }}/targets_tor-relay.yaml"
        state: "{{ (tor_metrics and tor_bridge_distribution | length == 0) |
          ternary('present', 'absent') }}"
