---
- name: Upgrade
  ansible.builtin.apt:
    upgrade: full
    update_cache: true

- name: Reboot - upgrade
  ansible.builtin.import_tasks: reboot.yaml

- name: Release
  when: desired_release | length > 0 and desired_release != ansible_facts.distribution_release
  block:
    - name: New Debian release
      when: ansible_facts.distribution == 'Debian'
      block:
        - name: Adapt Debian sources
          changed_when: true
          ansible.builtin.shell:
            cmd: |-
              sed -i -e 's/{{ ansible_facts.distribution_release }}/{{ desired_release }}/g' \
                /etc/apt/sources.list /etc/apt/sources.list.d/*

        - name: Upgrade Debian release
          async: 1200
          poll: 60
          ansible.builtin.apt:
            upgrade: dist
            update_cache: true

        - name: Finish Debian release
          when: ansible_facts.distribution == 'Debian' and ansible_facts.distribution_release != "bullseye"
          changed_when: true
          ansible.builtin.command:
            cmd: |-
              apt -y modernize-sources

    - name: Upgrade Ubuntu release
      environment:
        RELEASE_UPGRADE_NONINTERACTIVE: "1"
      when: ansible_facts.distribution == 'Ubuntu'
      changed_when: true
      async: 1200
      poll: 60
      ansible.builtin.command:
        cmd: |-
          do-release-upgrade -f DistUpgradeViewNonInteractive -d

    - name: Reboot - upgrade
      ansible.builtin.import_tasks: reboot.yaml

    - name: Gather facts - upgrade
      ansible.builtin.setup:
        gather_subset:
          - kernel
          - distribution_release
