---
- name: Restart Tor
  listen: Restart Tor
  ansible.builtin.systemd_service:
    name: tor
    state: restarted
    enabled: true
    daemon_reload: true

- name: Reload Tor
  listen: Reload Tor
  ansible.builtin.systemd_service:
    name: tor
    state: reloaded
    enabled: true
    daemon_reload: true

- name: Restart metrics
  listen: Restart metrics
  changed_when: true
  ansible.builtin.shell:
    cmd: |-
      pkill -9 -x metrics.sh
      echo 'nice /root/metrics.sh 15 /var/www/metrics-ddos &' | at now

- name: Restart watchdog
  listen: Restart watchdog
  changed_when: true
  ansible.builtin.shell:
    cmd: |-
      pkill -9 -x watchdog.sh
      echo 'nice /root/watchdog.sh &' | at now
