---
- name: Main
  module_defaults:
    ansible.builtin.lineinfile:
      create: true
      firstmatch: true
      mode: "0644"
  block:
    - name: Ping
      ansible.builtin.import_tasks: ping.yaml
      tags:
        - ping
