---
- name: SSH ping
  ignore_unreachable: true
  retries: 1
  delay: 30
  ansible.builtin.ping:
  register: ping

- name: Is down
  when: ping is unreachable
  block:
    - name: Ping hetzner
      delegate_to: localhost
      throttle: "{{ concurrent_local_jobs }}"
      changed_when: false
      ansible.builtin.command:
        cmd: >-
          ping -c 3 hetzner.de

    - name: Reset connection
      ansible.builtin.meta: reset_connection

    - name: Set is_down
      delegate_to: localhost
      throttle: 1
      ansible.builtin.lineinfile:
        line: "{{ inventory_hostname }}"
        path: "{{ infodir }}/is_down"

    - name: Failed
      ansible.builtin.fail:
        msg: ping

- name: Unset is_down
  delegate_to: localhost
  throttle: 1
  ansible.builtin.lineinfile:
    line: "{{ inventory_hostname }}"
    path: "{{ infodir }}/is_down"
    state: absent
