---
- name: Install/Update unattended software
  ansible.builtin.apt:
    name:
      - unattended-upgrades

- name: Configure needrestart
  ansible.builtin.lineinfile:
    line: "$nrconf{restart} = 'a';"
    path: /etc/needrestart/conf.d/auto-restart.conf

- name: Create timer.d directories
  ansible.builtin.file:
    state: directory
    path: "/etc/systemd/system/{{ item }}"
    mode: "0755"
  loop:
    - apt-daily.timer.d/
    - apt-daily-upgrade.timer.d/

# 2x per day at :02
- name: Configure apt update timer
  ansible.builtin.template:
    src: apt_update.j2
    dest: /etc/systemd/system/apt-daily.timer.d/override.conf
  notify: Reload systemd

# 2x per day at :15
- name: Configure apt upgrade timer
  ansible.builtin.template:
    src: apt_upgrade.j2
    dest: /etc/systemd/system/apt-daily-upgrade.timer.d/override.conf
  notify: Reload systemd

# 2x per day between :40 and :50
- name: Ensure needrestart cron job is present
  vars:
    _check_cmd: >-
      {{
      (ansible_facts.distribution_release in ('bullseye', 'bookworm', 'jammy', 'noble')) |
      ternary('pgrep -x sshd | grep -v /usr/sbin/sshd | grep -v grep', 'pgrep -x sshd-session')
      }}
  ansible.builtin.cron:
    name: Reboot if needrestart advised it
    hour: "{{ timer_hour1 }},{{ timer_hour2 }}"
    minute: "{{ 40 + 10 | random(seed=seed_host) }}"
    job: >-
      if
      [[ -f /var/run/reboot-required ]] ||
      LC_ALL=C.UTF-8 needrestart -r l -b | grep -q -e 'NEEDRESTART-KSTA: 2' -e 'NEEDRESTART-KSTA: 3';
      then
      {{ _check_cmd }} || reboot;
      else
      LC_ALL=C.UTF-8 needrestart -r a -b;
      fi

# 2x per day at :58
- name: Ensure reaper cron job is present
  ansible.builtin.cron:
    name: Reap a hanging apt process
    hour: "{{ timer_hour1 }},{{ timer_hour2 }}"
    minute: 58
    job: >-
      pkill -f "apt-get -qq -y update"

# https://unix.stackexchange.com/questions/178626/how-to-run-unattended-upgrades-not-daily-but-every-few-hours
- name: Configure
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/apt/apt.conf.d/
  loop:
    - 20auto-upgrades
    - 50unattended-upgrades
  notify: Reload systemd

- name: Enable and start
  failed_when: false
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - apt-daily.timer
    - apt-daily-upgrade.timer
    - unattended-upgrades
