---
- name: Main
  module_defaults:
    ansible.builtin.apt:
      allow_change_held_packages: true
      autoclean: true
      autoremove: true
      purge: true
      state: latest
    ansible.builtin.copy:
      mode: "0644"
    ansible.builtin.cron:
      backup: true
    ansible.builtin.file:
      mode: "0644"
    ansible.builtin.lineinfile:
      create: true
      firstmatch: true
      mode: "0644"
    ansible.builtin.template:
      mode: "0644"
  block:
    - name: Configure Debian
      when: ansible_facts.os_family == 'Debian'
      ansible.builtin.import_tasks: autoupdate-apt.yaml
      tags:
        - autoupdate

    - name: Flush handlers (autoupdate)
      ansible.builtin.meta: flush_handlers
      tags:
        - flush
