# Ansible managed

# the filesystem is r-o after reboot
[Service]
ExecStart=
ExecStart=/bin/sh -c 'if nft -o -f /var/lib/nftables/rules-save; then \
  rm -f /var/lib/nftables/rules-save || true; else nft -o -f /etc/nftables.conf; fi'

ExecStop=
ExecStop=/bin/sh -c '{ echo "#!/usr/sbin/nft -f"; echo "flush ruleset"; \
  nft -s list ruleset; } >/var/lib/nftables/rules-save; \
  nft flush ruleset'

ExecReload=
ExecReload=/bin/sh -c '{ echo "#!/usr/sbin/nft -f"; echo "flush ruleset"; \
  nft list ruleset; } >/var/lib/nftables/rules-save; \
  nft -o -f /var/lib/nftables/rules-save; rm -f /var/lib/nftables/rules-save'
