---
- name: Halt
  changed_when: _halt.shutdown | default(false)
  ignore_unreachable: true
  retries: 3
  delay: 10
  community.general.shutdown:
  register: _halt

- name: Additional wait
  delegate_to: localhost
  ansible.builtin.wait_for:
    timeout: 20
