---
- name: Sum connections
  changed_when: false
  ansible.builtin.shell:
    cmd: |-
      set -eu

      equatation=$(
        journalctl -u snowflake --since "{{ log_connections_seconds_ago }} second ago" \
          -g ', there were .* connections' --quiet |
        awk '{ print $14 }' |
        xargs -r |
        tr ' ' '+'
      )
      if [[ -n $equatation ]]; then
        printf "%5s\n" $(( equatation ))
      else
        echo "n/a"
      fi
    executable: /bin/bash
  register: _result_connections_snowflake

- name: File connections
  delegate_to: localhost
  throttle: 1
  ansible.builtin.lineinfile:
    line: "{{ inventory_hostname }} {{ _result_connections_snowflake.stdout }}"
    path: "{{ infodir }}/snowflake_connections"
    regexp: "^{{ inventory_hostname }} "
