---
- name: Main
  when: is_snowflake
  module_defaults:
    ansible.builtin.lineinfile:
      create: true
      firstmatch: true
  block:
    - name: Connections
      ansible.builtin.import_tasks: _connections.yaml
      tags:
        - connections

    - name: Log NAT
      ansible.builtin.import_tasks: _log-nat.yaml
      tags:
        - log-nat

    - name: Log proxy
      ansible.builtin.import_tasks: _log-proxy.yaml
      tags:
        - log-proxy

    - name: Process runtime
      ansible.builtin.import_tasks: _process-runtime.yaml
      tags:
        - process-runtime

    - name: Systemd time
      ansible.builtin.import_tasks: _systemd-time.yaml
      tags:
        - systemd-time

    - name: Version of Snowflake
      ansible.builtin.import_tasks: _version.yaml
      tags:
        - version
