---
- name: Snowflake version
  changed_when: false
  ansible.builtin.shell:
    cmd: |-
      /usr/bin/snowflake --version 2>&1 |
        head -n 1 |
        cut -f 2- -d ' ' |
        tr ' ' '_'
  register: _result_sf_version

- name: File version
  delegate_to: localhost
  throttle: 1
  vars:
    _version: "{{ _result_sf_version.stdout | default('-') }}"
  ansible.builtin.lineinfile:
    line: "{{ inventory_hostname }} sf {{ _version }}"
    path: "{{ infodir }}/snowflake_version"
    regexp: "^{{ inventory_hostname }} "
