---
- name: Load needed kernel modules
  changed_when: true
  ansible.builtin.shell:
    cmd: |-
      set -euf

      ipt="iptables"
      $ipt -A INPUT -p tcp -m multiport --dports 1234,1235 -j ACCEPT

      ipt="ip6tables"
      $ipt -A INPUT -p tcp -m multiport --dports 1236,1237 -j ACCEPT

      # reset Base firewall
      /root/firewall-ipv4.sh start
      /root/firewall-ipv6.sh start
