---
- name: Firewall Image
  ansible.builtin.import_tasks: firewall-image.yaml
  tags:
    - firewall-image

- name: Clone repos
  ansible.builtin.import_tasks: clone-repos.yaml
  tags:
    - clone-repos

- name: Install golang
  ansible.builtin.import_tasks: golang.yaml
  tags:
    - golang
    - never

- name: Services
  ansible.builtin.import_tasks: services.yaml
  tags:
    - services
