---
- name: SSH ping
  ignore_errors: true
  ignore_unreachable: true
  changed_when: false
  ansible.builtin.ping:
  register: _ssh_ping

- name: Block
  when: _ssh_ping.unreachable is defined or _ssh_ping.ping is not defined or _ssh_ping.ping != 'pong'
  block:
    - name: Ensure that localhost network is ok
      delegate_to: localhost
      throttle: "{{ concurrent_local_jobs }}"
      changed_when: false
      ansible.builtin.command:
        cmd: >-
          ping -c 3 hetzner.de

    - name: System is down
      delegate_to: localhost
      throttle: 1
      ansible.builtin.lineinfile:
        line: "{{ inventory_hostname }}"
        path: "{{ infodir }}/is_down"

    - name: Poweron
      delegate_to: localhost
      throttle: "{{ concurrent_local_jobs }}"
      changed_when: true
      environment:
        PATH: "{{ lookup('env', 'PATH') }}:{{ lookup('env', 'HOME') }}/bin"
      ansible.builtin.command:
        cmd: >-
          hcloud --quiet --poll-interval 10s server poweron {{ inventory_hostname }}

    - name: Wait for bootup
      delegate_to: localhost
      ansible.builtin.wait_for:
        timeout: 25

    - name: SSH ping after poweron
      ansible.builtin.ping:

    - name: System is up
      delegate_to: localhost
      throttle: 1
      ansible.builtin.lineinfile:
        line: "{{ inventory_hostname }}"
        path: "{{ infodir }}/is_down"
        state: absent
