---
- name: Install/Update tools for DDoS
  ansible.builtin.apt:
    name:
      - jq

- name: Fetch
  throttle: 8
  block:
    - name: Get DDoS scripts
      retries: 1
      ansible.builtin.get_url:
        url: "{{ torutils_path }}/{{ item }}"
        dest: /root/
      loop:
        - ipv4-rules.sh
        - ipv6-rules.sh
        - ipv4-rules-egress.sh

- name: Trigger kernel iptables module load
  changed_when: false
  ansible.builtin.shell:
    cmd: |-
      set -euf

      # DDoS
      export CONFIGURED_RELAYS="{{ ansible_facts.default_ipv4.address }}:1234"
      export CONFIGURED_RELAYS6="[{{ ansible_facts.default_ipv6.address }}]:5678"

      /root/ipv4-rules.sh start
      /root/ipv6-rules.sh start

      /root/ipv4-rules-egress.sh start

      # Base
      /root/firewall-ipv4.sh start
      /root/firewall-ipv6.sh start

      # Snowflake
      iptables -A INPUT -p udp --dst {{ ansible_facts.default_ipv4.address }} --match multiport --dports 32768:60999 -j ACCEPT
