---
- name: Main
  when: kernel_git_repo_url | length > 0
  module_defaults:
    ansible.builtin.copy:
      mode: "0644"
    ansible.builtin.get_url:
      mode: "0744"
      force: true
  block:
    - name: Validate
      ansible.builtin.import_tasks: validate.yaml
      tags:
        - always
        - validate

    - name: Tools
      ansible.builtin.import_tasks: tools.yaml
      tags:
        - tools

    - name: Check for running kernel build process
      community.general.pids:
        name: build-kernel.sh
      register: _build_is_running
      tags:
        - kernel-build

    - name: Build
      when: _build_is_running.pids | default([]) | length == 0
      tags:
        - kernel-build
      block:
        - name: Git
          vars:
            _git_repo_url: "{{ kernel_git_repo_url }}"
            _git_version: "{{ kernel_git_version }}"
            _git_patches: "{{ kernel_git_patches }}"
            _repo_dir: /root/linux
          ansible.builtin.include_tasks: "{{ role_path }}/../../../playbooks/roles/lib/_git.yaml"

        - name: Build kernel
          when: kernel_build or not is_image
          ansible.builtin.import_tasks: kernel-build.yaml
