---
- name: Install/Update toolchain
  ansible.builtin.apt:
    name:
      - bc
      - bison
      - build-essential
      - cpio
      - dwarves
      - flex
      - kmod
      - libelf-dev
      - libncurses5-dev
      - libssl-dev
      - lz4

- name: Install/Update toolchain for Ubuntu
  when: ansible_facts.distribution_release == 'resolute'
  ansible.builtin.apt:
    name:
      - libdw-dev
