---
- name: Install/Update toolchain
  ansible.builtin.apt:
    name:
      - bc
      - bison
      - build-essential
      - cpio
      - dwarves
      - flex
      - kmod
      - libelf-dev
      - libncurses5-dev
      - libssl-dev
      - lz4

- name: Do not upgrade kernel dist package
  when: not is_image
  changed_when: false
  vars:
    _arch: "{{ (ansible_facts.architecture == 'x86_64') | ternary('amd64', 'arm64') }}"
    _cloud: "{{ kernel_debian_cloud | ternary('-cloud', '') }}"
    _suffix: "{{ (ansible_facts.distribution == 'Debian') | ternary(_cloud ~ '-' ~ _arch, '-virtual') }}"
  ansible.builtin.command:
    cmd: |-
      apt-mark hold linux-image{{ _suffix }}
