---
- name: Snapshot
  delegate_to: localhost
  throttle: "{{ concurrent_local_jobs }}"
  block:
    - name: Create image
      changed_when: true
      ansible.builtin.command:
        cmd: >-
          hcloud --quiet --poll-interval 10s server create-image
            --type snapshot --description='{{ snapshot_description }}' {{ inventory_hostname }}

  always:
    - name: Delete outdated
      changed_when: _at.stdout | length > 0
      ansible.builtin.shell:
        cmd: |-
          hcloud --quiet image list --type snapshot --output noheader --output columns=id,description |
            grep -e " {{ snapshot_description }}[ ]*$" |
            sort -rn |
            awk 'x[$2]++ { print $1 }' |
            xargs -r echo hcloud --quiet --poll-interval 10s image delete |
            while read -r cmd; do
              # use at to avoid a race with a parallel running create/rebuild job
              echo $cmd | at now + 15 min
            done
      register: _at
