---
- name: Add the group
  ansible.builtin.group:
    name: snowflake

- name: Add the user
  ansible.builtin.user:
    group: snowflake
    name: snowflake
    create_home: false

- name: Git
  vars:
    _git_repo_url: https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake.git
    _git_version: "{{ snowflake_git_version }}"
    _git_patches: "{{ snowflake_git_patches }}"
    _repo_dir: /root/snowflake
  ansible.builtin.include_tasks: "{{ role_path }}/../../../playbooks/roles/lib/_git.yaml"

- name: Build
  throttle: 16
  changed_when: false
  vars:
    _cmd: go build -v
  ansible.builtin.shell:
    cmd: |-
      if ! {{ _cmd }}; then
        if ! GOPROXY="https://goproxy.io" {{ _cmd }}; then
          GOPROXY="direct" {{ _cmd }}
        fi
      fi
    chdir: /root/snowflake/proxy

- name: Copy
  ansible.builtin.copy:
    src: /root/snowflake/proxy/proxy
    dest: /usr/bin/snowflake
    mode: a+x
    remote_src: true
  notify: Restart snowflake

- name: Add/Change systemd unit
  ansible.builtin.template:
    src: snowflake-proxy.service.j2
    dest: /etc/systemd/system/snowflake.service
  notify: Restart snowflake

- name: Enable
  ansible.builtin.systemd_service:
    name: snowflake
    enabled: true
  notify: Restart snowflake
