{
 "title": "Tor Snowflake hx",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "Job",
    "label": "Job",
    "query": {
     "query": "label_values(tor_snowflake_proxy_connections_total,job)"
    }
   },
   {
    "name": "t1",
    "label": "Prefix",
    "query": {
     "query": "label_values(tor_snowflake_proxy_connections_total{job=~\"$Job\"},t1)"
    }
   },
   {
    "name": "t2",
    "label": "OS",
    "query": {
     "query": "label_values(tor_snowflake_proxy_connections_total{job=~\"$Job\", t1=~\"$t1\"},t2)"
    }
   },
   {
    "name": "t3",
    "label": "Arch",
    "query": {
     "query": "label_values(tor_snowflake_proxy_connections_total{job=~\"$Job\", t1=~\"$t1\", t2=~\"$t2\"},t3)"
    }
   },
   {
    "name": "t4",
    "label": "Kernel",
    "query": {
     "query": "label_values(tor_snowflake_proxy_connections_total{job=~\"$Job\", t1=~\"$t1\", t2=~\"$t2\", t3=~\"$t3\"},t4)"
    }
   },
   {
    "name": "t5",
    "query": {
     "query": "label_values(tor_snowflake_proxy_connections_total{job=~\"$Job\", t1=~\"$t1\", t2=~\"$t2\", t3=~\"$t3\", t4=~\"$t4\"},t5)"
    }
   },
   {
    "name": "t6",
    "query": {
     "query": "label_values(tor_snowflake_proxy_connections_total{job=~\"$Job\", t1=~\"$t1\", t2=~\"$t2\", t3=~\"$t3\", t4=~\"$t4\", t5=~\"$t5\"},t6)"
    }
   },
   {
    "name": "t7",
    "query": {
     "query": "label_values(tor_snowflake_proxy_connections_total{job=~\"$Job\", t1=~\"$t1\", t2=~\"$t2\", t3=~\"$t3\", t4=~\"$t4\", t5=~\"$t5\", t6=~\"$t6\"},t7)"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(tor_snowflake_proxy_connections_total{job=~\"$Job\", t1=~\"$t1\", t2=~\"$t2\", t3=~\"$t3\", t4=~\"$t4\", t5=~\"$t5\", t6=~\"$t6\", t7=~\"$t7\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Targets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Targets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "prometheus_sd_discovered_targets{config=~\"$Job\"}",
     "legendFormat": "{{config}}"
    }
   ]
  },
  {
   "title": "Uname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(release) (node_uname_info{job=~\"$Job\", instance=~\"$Instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Connections per hr",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(tor_snowflake_proxy_connections_total{instance=~\"$Instance\", job=~\"$Job\"}[$__rate_interval])) * 3600",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "sum(rate(tor_snowflake_proxy_traffic_inbound_bytes_total{instance=~\"$Instance\", job=~\"$Job\"}[$__rate_interval]))",
     "legendFormat": "inbound"
    },
    {
     "expr": "sum(rate(tor_snowflake_proxy_traffic_outbound_bytes_total{instance=~\"$Instance\", job=~\"$Job\"}[$__rate_interval]))",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "Connection Timeouts per hr",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(tor_snowflake_proxy_connection_timeouts_total{instance=~\"$Instance\", job=~\"$Job\"}[$__rate_interval])) * 3600",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=~\"$Instance\", job=~\"$Job\"}[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Avg", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Connections per hr",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(avg by(country) (rate(tor_snowflake_proxy_connections_total{instance=~\"$Instance\", job=~\"$Job\"}[$__rate_interval]))) * 3600",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "avg(rate(tor_snowflake_proxy_traffic_inbound_bytes_total{instance=~\"$Instance\", job=~\"$Job\"}[$__rate_interval]))",
     "legendFormat": "inbound"
    },
    {
     "expr": "avg(rate(tor_snowflake_proxy_traffic_outbound_bytes_total{instance=~\"$Instance\", job=~\"$Job\"}[$__rate_interval]))",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "Connections per hr per country",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(country) (avg by(country) (rate(tor_snowflake_proxy_connections_total{instance=~\"$Instance\", job=~\"$Job\"}[$__rate_interval]))) * 3600",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(avg(rate(process_cpu_seconds_total{instance=~\"$Instance\", job=~\"$Job\"}[$__rate_interval])))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Connections per hr",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(tor_snowflake_proxy_connections_total{instance=~\"$Instance\", job=~\"$Job\"}[5m])) * 3600",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Traffic Inbound",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(tor_snowflake_proxy_traffic_inbound_bytes_total{instance=~\"$Instance\", job=~\"$Job\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open Fds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$Instance\", job=~\"$Job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Traffic Outbound",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(tor_snowflake_proxy_traffic_outbound_bytes_total{instance=~\"$Instance\", job=~\"$Job\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$Instance\", job=~\"$Job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(process_cpu_seconds_total{instance=~\"$Instance\", job=~\"$Job\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}