---
#  (up to) last 3 days (sorted from newest to oldest)
- name: Get unique clients of a bridge
  changed_when: false
  ansible.builtin.shell:
    cmd: |-
      zgrep -h -F ' unique clients.' \
        notice.log.3.gz notice.log.2.gz notice.log.1 notice.log |
        tail -n 12 |
        cut -f 2- -d ',' |
        grep -Eo ' [0-9]+ ' |
        tac |
        xargs -r printf "%4s %4s %4s %4s %4s %4s %4s %4s %4s %4s %4s %4s\n" |
        sed 's,  *$,,'
    chdir: /var/log/tor/
    executable: /bin/bash
  register: _result_tor_clients

- name: File clients of a bridge
  delegate_to: localhost
  throttle: 1
  ansible.builtin.lineinfile:
    line: "{{ inventory_hostname }} {{ _result_tor_clients.stdout }}"
    path: "{{ infodir }}/tor_clients"
    regexp: "^{{ inventory_hostname }} "
    state: "{{ (_result_tor_clients.stdout | length > 0) | ternary('present', 'absent') }}"
