---
- name: Get connections of a server
  changed_when: false
  vars:
    log_notice: /var/log/tor/notice.log
  ansible.builtin.shell:
    cmd: |-
      grep -h -Eo 'initiated [0-9]+ and received [0-9]+ v. connections' {{ log_notice }}.1 {{ log_notice }} |
        awk '{ print $2, $5 }' |
        xargs -r -n 10 |
        while read line; do echo $line | tr ' ' '+' | bc; done |
        tac |
        xargs -r
  register: _result_connections_tor

- name: File connections of a server
  delegate_to: localhost
  throttle: 1
  ansible.builtin.lineinfile:
    line: "{{ inventory_hostname }} {{ _result_connections_tor.stdout | default('n/a') }}"
    path: "{{ infodir }}/tor_connections"
    regexp: "^{{ inventory_hostname }} "
