---
- name: Create local firewall info directory
  delegate_to: localhost
  throttle: "{{ concurrent_local_jobs }}"
  ansible.builtin.file:
    state: directory
    path: "{{ infodir }}/fw/{{ inventory_hostname }}/"
    mode: "0755"

- name: DDoS Ipset
  tags:
    - ddos-ipset
  block:
    - name: Get DDoS ipset
      changed_when: false
      ansible.builtin.shell:
        cmd: |-
          name=$(ipset list -n | grep "^torutils-ddos-{{ item }}-")
          ipset list $name | cut -f 1 -d ' ' | sed -e '1,8d'
      loop_control:
        label: "{{ inventory_hostname }} {{ item }}"
      loop:
        - v4
        - v6
      register: _ipset_ddos

    - name: Save DDoS ipset
      delegate_to: localhost
      throttle: "{{ concurrent_local_jobs }}"
      ansible.builtin.copy:
        content: "{{ item.stdout }}"
        dest: "{{ infodir }}/fw/{{ inventory_hostname }}/torutils-ddos-{{ item.item }}"
      loop_control:
        label: "{{ inventory_hostname }} {{ item.item }}"
      loop: "{{ _ipset_ddos.results }}"

- name: DDoS Hash
  tags:
    - ddos-hash
    - never
  block:
    - name: Get DDoS hash name
      ansible.builtin.find:
        paths:
          - /proc/net/ipt_hashlimit/
          - /proc/net/ip6t_hashlimit/
        patterns: torutils-ddos-v*
        file_type: file
      register: ddos_hash

    - name: Fetch DDoS hash
      throttle: "{{ concurrent_local_jobs }}"
      vars:
        _destfname: "{{ item.path | basename | regex_replace('-\\d{3,5}-', '-orport-') }}"
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: "{{ infodir }}/fw/{{ inventory_hostname }}/{{ _destfname }}"
        validate_checksum: false
      loop_control:
        label: "{{ _destfname }}"
      loop: "{{ ddos_hash.files | default([]) }}"
