---
- name: Create local firewall info directory
  delegate_to: localhost
  throttle: "{{ concurrent_local_jobs }}"
  ansible.builtin.file:
    state: directory
    path: "{{ infodir }}/fw/{{ inventory_hostname }}/"
    mode: "0755"

- name: DDoS Ipset save
  tags:
    - ddos-ipset-save
    - never
  block:
    - name: Trigger DDoS save
      changed_when: true
      ansible.builtin.shell:
        cmd: |-
          set -euf

          /root/ipv4-rules.sh save
          /root/ipv6-rules.sh save

- name: DDoS Ipset fetch
  tags:
    - ddos-ipset
  block:
    - name: Get DDoS ipset file name
      ansible.builtin.find:
        paths: /var/tmp/
        patterns: torutils-ddos-v*
        file_type: file
        age: "-1h"
        age_stamp: atime
      register: ddos_ipset

    - name: Fetch DDoS ipset
      throttle: "{{ concurrent_local_jobs }}"
      vars:
        _destfname: "{{ item.path | basename | regex_replace('-\\d{3,5}-', '-snip-') }}"
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: "{{ infodir }}/fw/{{ inventory_hostname }}/{{ _destfname }}"
      loop_control:
        label: "{{ _destfname }}"
      loop: "{{ ddos_ipset.files | default([]) }}"

- name: Hash
  tags:
    - ddos-hash
    - never
  block:
    - name: Get DDoS hash name
      ansible.builtin.find:
        paths:
          - /proc/net/ipt_hashlimit/
          - /proc/net/ip6t_hashlimit/
        patterns: torutils-ddos-v*
        file_type: file
      register: ddos_hash

    - name: Fetch DDoS hash
      throttle: "{{ concurrent_local_jobs }}"
      vars:
        _destfname: "{{ item.path | basename | regex_replace('-\\d{3,5}-', '-snip-') }}"
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: "{{ infodir }}/fw/{{ inventory_hostname }}/{{ _destfname }}"
        validate_checksum: false
      loop_control:
        label: "{{ _destfname }}"
      loop: "{{ ddos_hash.files | default([]) }}"
