---
- name: Get fingerprint
  changed_when: false
  ansible.builtin.command:
    cmd: >-
      cut -f 2 -d ' ' /var/lib/tor/fingerprint
  register: _result_fp

- name: Get ED25519 fingerprint
  changed_when: false
  ansible.builtin.command:
    cmd: >-
      cut -f 2 -d ' ' /var/lib/tor/fingerprint-ed25519
  register: _result_fp_ed25519

- name: Get hashed fingerprint of a bridge
  when: tor_bridge_distribution | length > 0
  changed_when: false
  ansible.builtin.command:
    cmd: >-
      cut -f 2 -d ' ' /var/lib/tor/hashed-fingerprint
  register: _result_fp_hashed
