---
- name: Check warn log
  changed_when: false
  ansible.builtin.shell:
    cmd: |-
      grep -h -v \
        -e 'opening .*log file.' \
        -e 'Please upgrade! This version of Tor' \
        -e 'The IPv4 ORPort address 127.0.0.1 does not match' \
        -e 'Unrecognized BridgeDistribution value' \
         warn.log.1 warn.log |
        tail -n 10 |
        {{ filter_sensitive_data }}
    chdir: /var/log/tor/
    executable: /bin/bash
  register: _result_log_warn

- name: Results of warn log
  when: _result_log_warn.stdout | length > 0
  changed_when: true
  ansible.builtin.debug:
    var: _result_log_warn.stdout_lines
