---
artefact_paths: []
artefact_patterns: []
artefact_limit: 20
artefact_size: "-20m"

coredump_paths:
  - /var/crash/minicoredumper
coredump_patterns:
  - core.tar.gz
coredump_limit: 200

issue_since: ""

trace_since: ""

filter_sensitive_data: "tee"

is_tor: false
