---
- name: Get conntrack drop value
  changed_when: false
  ansible.builtin.shell:
    cmd: |-
      conntrack -S |
        head -n $(nproc) |
        grep -v ' insert_failed=0 drop=0 ' |
        cut -f 2- -d ':'
  register: _result_ct_drop

- name: File conntrack drop value
  delegate_to: localhost
  throttle: 1
  ansible.builtin.lineinfile:
    line: "{{ inventory_hostname }} {{ _result_ct_drop.stdout }}"
    path: "{{ infodir }}/conntrack"
    regexp: "^{{ inventory_hostname }} "
