---
- name: Histogram of all drop sets
  changed_when: false
  ansible.builtin.shell:
    cmd: |-
      nft -j -ns list ruleset | python3 -c '
      import sys, json

      try:
          data = json.load(sys.stdin)
      except Exception as e:
          print(f"load error: {e}")
          sys.exit(1)

      sets = [
          item["set"] for item in data.get("nftables", [])
          if "set" in item and "{{ firewall_set_pattern }}" in item["set"].get("name", "").lower()
      ]

      if not sets:
          print("no set founds with \"{{ firewall_set_pattern }}\".")
          sys.exit()

      # init
      histogram = {s["name"]: [0] * 24 for s in sets}

      for s in sets:
          for elem in s.get("elem", []):
              expires = None
              if isinstance(elem, dict):
                  inner_elem = elem.get("elem", {})
                  if isinstance(inner_elem, dict):
                      expires = inner_elem.get("expires")
                  else:
                      expires = elem.get("expires")

              if expires is not None:
                  try:
                      hours = int(expires // 3600)
                      if 0 <= hours < 24:
                          histogram[s["name"]][hours] += 1
                  except (ValueError, TypeError):
                      continue

      # print table header
      names = list(histogram.keys())

      header = "tout | " + " | ".join(f"{name:>25}" for name in names) + " |"
      print(header)
      print("-" * len(header))

      # hours 0-23
      for hours in range(24):
          row_values = [f"{histogram[name][hours]:>25}" for name in names]
          print(f"{hours:>4} | " + " | ".join(row_values) + " |")

      '
  register: _result_histogram

- name: Output of Histogram
  throttle: 1
  when: _result_histogram.stdout | length > 0
  changed_when: true
  ansible.builtin.debug:
    var: _result_histogram.stdout_lines
