---
- name: Get nginx log
  changed_when: false
  ansible.builtin.shell:
    cmd: >-
      tail -q -n 10 /var/log/nginx/{{ nginx_loglevel | default('error') }}.log{,.1} |
        grep -v ': using inherited sockets from '
        sort |
        tail -n 10
    executable: /bin/bash
  register: _result_nginx

- name: Results of nginx log
  when: _result_nginx.stdout | length > 0
  changed_when: true
  ansible.builtin.debug:
    var: _result_nginx.stdout_lines
