---
- name: Main
  module_defaults:
    ansible.builtin.fetch:
      flat: true
    ansible.builtin.lineinfile:
      create: true
      firstmatch: true
      mode: "0644"
  block:
    - name: Conntrack
      ansible.builtin.import_tasks: conntrack.yaml
      tags:
        - conntrack

    - name: Dry run
      ansible.builtin.import_tasks: dryrun-unattended.yaml
      tags:
        - dryrun-unattended
        - never

    - name: Firewall histogram
      ansible.builtin.import_tasks: firewall-histogram.yaml
      tags:
        - firewall-histogram
        - never

    - name: Firewall stats
      ansible.builtin.import_tasks: firewall-stats.yaml
      tags:
        - firewall-stats
        - never

    - name: Log unattended
      ansible.builtin.import_tasks: log-unattended.yaml
      tags:
        - log-unattended

    - name: Log nginx error
      ansible.builtin.import_tasks: log-nginx.yaml
      tags:
        - log-nginx

    - name: Uname
      ansible.builtin.import_tasks: uname.yaml
      tags:
        - uname

    - name: Uptime
      ansible.builtin.import_tasks: uptime.yaml
      tags:
        - uptime
