---
- name: Create local firewall info directory
  delegate_to: localhost
  throttle: "{{ concurrent_local_jobs }}"
  ansible.builtin.file:
    state: directory
    path: "{{ infodir }}/fw/{{ inventory_hostname }}/"
    mode: "0755"

- name: Get Tarpit ipset
  changed_when: false
  ansible.builtin.shell:
    cmd: |-
      ipset list torutils-tarpit-{{ item }} | cut -f 1 -d ' ' | sed -e '1,8d'
  loop_control:
    label: "{{ inventory_hostname }} {{ item }}"
  loop:
    - v4
    - v6
  register: _ipset_tarpit

- name: Save Tarpit ipset
  delegate_to: localhost
  throttle: "{{ concurrent_local_jobs }}"
  ansible.builtin.copy:
    content: "{{ item.stdout }}"
    dest: "{{ infodir }}/fw/{{ inventory_hostname }}/torutils-tarpit-{{ item.item }}"
  loop_control:
    label: "{{ inventory_hostname }} {{ item.item }}"
  loop: "{{ _ipset_tarpit.results }}"
