---
- name: Setup
  hosts: all
  order: shuffle
  roles:
    - role: poweron
    - role: setup_common
    - role: setup_snowflake
    - role: setup_tor
    - role: setup_kernel
    - role: setup_autoupdate
    - role: info_healthy
