---
- name: Test common
  hosts: hx
  order: shuffle
  roles:
    - role: poweron
    - role: setup_common
    - role: setup_snowflake
    - role: setup_tor
    - role: setup_kernel
    - role: setup_autoupdate
    - role: info_common
    - role: info_snowflake
    - role: info_tor
    - role: info_healthy
    - role: shutdown
    - role: delete
