---
- name: Get DDoS metrics script
  throttle: 16
  retries: 1
  ansible.builtin.get_url:
    url: "{{ torutils_path }}/metrics.sh"
    dest: /root/
  notify: Restart metrics

- name: Create nginx metrics-ddos
  ansible.builtin.file:
    path: /var/www/metrics-ddos
    state: directory
    group: www-data
    mode: "0750"
  notify: Restart metrics

- name: Cron job for DDoS metrics
  ansible.builtin.cron:
    name: DDoS metrics
    special_time: reboot
    job: >-
      nice /root/metrics.sh 15 /var/www/metrics-ddos
    state: "{{ ddos_metrics | ternary('present', 'absent') }}"
  notify: Restart metrics

- name: Get metrics.sh pid if any
  changed_when: _metrics.pids | default([]) | length == 0
  community.general.pids:
    name: metrics.sh
  notify: Restart metrics
