---
- name: Get DDoS metrics script
  throttle: 16
  retries: 1
  ansible.builtin.get_url:
    url: "{{ torutils_path }}/metrics.sh"
    dest: /root/
  register: _download_metrics

- name: Create nginx metrics-ddos
  ansible.builtin.file:
    path: /var/www/metrics-ddos
    state: directory
    group: www-data
    mode: "0750"

- name: Cron job for DDoS metrics
  ansible.builtin.cron:
    name: DDoS metrics
    special_time: reboot
    job: >-
      nice /root/metrics.sh 15 /var/www/metrics-ddos
    state: "{{ ddos_metrics | ternary('present', 'absent') }}"
  register: _cronjob

- name: Get metrics.sh pid if any
  community.general.pids:
    name: metrics.sh
  register: _metrics_pids_running

- name: Ensure recent metrics.sh is running
  when: _download_metrics.changed or _metrics_pids_running.pids | default([]) | length == 0
  changed_when: true
  ansible.builtin.shell:
    cmd: |-
      set -euf

      # pkill won't work in an ansible task
      pids=$(echo {{ _metrics_pids_running.pids | default([]) | join(' ') }} | xargs -r -n 1)
      if [[ -n $pids ]]; then
        for p in $pids; do
          if ! kill $p; then
            : vanished
          fi
        done
      fi

      echo 'nice /root/metrics.sh 15 /var/www/metrics-ddos &' | at now
    executable: /bin/bash
