---
- name: Install/Update toolchain for Tor
  when: ansible_facts.os_family == 'Debian'
  ansible.builtin.apt:
    name:
      - automake
      - build-essential
      - libevent-dev
      - libssl-dev
      - logrotate
      - zlib1g-dev

- name: Install/Update toolchain for Tor relay
  when: tor_bridge_distribution | length == 0
  ansible.builtin.apt:
    name:
      - libseccomp-dev

- name: Install/Update toolchain for Tor under Ubuntu
  when: ansible_facts.distribution == 'Ubuntu'
  ansible.builtin.apt:
    name:
      - autotools-dev

- name: Install/Update toolchain for Tor bridge
  when: tor_bridge_distribution | length > 0
  ansible.builtin.include_tasks: "{{ role_path }}/../../../playbooks/roles/lib/_golang.yaml"
