---
# https://support.torproject.org/apt/tor-deb-repo/
- name: Repo
  vars:
    _key: A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc # gitleaks:allow
    _keyring: /usr/share/keyrings/deb.torproject.org-keyring.gpg
    _uri: https://deb.torproject.org/torproject.org
  block:
    - name: Enable repository for trixie
      when: ansible_facts.distribution_release == 'trixie'
      ansible.builtin.deb822_repository:
        name: tor
        types:
          - deb
          - deb-src
        uris: "{{ _uri }}"
        suites: "{{ ansible_facts.distribution_release }}"
        components: main
        signed_by: "{{ _uri }}/{{ _key }}"

    - name: Non-Trixie
      when: ansible_facts.distribution_release != 'trixie'
      block:
        - name: Enable legacy repository - apt
          ansible.builtin.apt:
            name:
              - apt-transport-https
              - gnupg

        - name: Enable legacy repository - gpg key
          ansible.builtin.shell:
            cmd: >-
              curl -q {{ _uri }}/{{ _key }} -o - |
                gpg --dearmor >"{{ _keyring }}"
            creates: "{{ _keyring }}"

        - name: Enable legacy repository - sources bookworm
          when: ansible_facts.distribution_release == 'bookworm'
          ansible.builtin.deb822_repository:
            name: tor
            types:
              - deb
              - deb-src
            uris: "{{ _uri }}"
            suites: "{{ ansible_facts.distribution_release }}"
            components: main
            signed_by: "{{ _keyring }}"

        - name: Enable legacy repository - sources Ubuntu
          when: ansible_facts.distribution == 'Ubuntu'
          ansible.builtin.apt_repository:
            repo: >-
              {{ item }} [signed-by={{ _keyring }}] {{ _uri }} {{ ansible_facts.distribution_release }} main
          loop:
            - deb
            - deb-src

- name: Update apt cache
  ansible.builtin.apt:
    cache_valid_time: 1
    update_cache: true

- name: Install/Update Tor
  ansible.builtin.apt:
    name:
      - deb.torproject.org-keyring
      - tor
      - tor-geoipdb
  notify: Restart Tor

- name: Install/Update PT
  when: tor_bridge_distribution | length > 0
  ansible.builtin.apt:
    name:
      - obfs4proxy
  notify: Restart Tor

# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1021911
- name: Allow low port for Tor
  when: tor_port < 1024
  vars:
    _exe: "{{ (tor_bridge_distribution | length > 0) | ternary('/usr/bin/obfs4proxy', '/usr/bin/tor') }}"
  ansible.builtin.lineinfile:
    line: >-
      DPkg::Post-Invoke { "setcap cap_net_bind_service=+ep {{ _exe }}"; };
    path: /etc/apt/apt.conf.d/99-tor-lowport
