---
# https://support.torproject.org/apt/tor-deb-repo/
- name: Repo
  vars:
    _key: A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc # gitleaks:allow
    _uri: https://deb.torproject.org/torproject.org
  block:
    - name: Repo
      block:
        - name: Add Tor repository
          ansible.builtin.deb822_repository:
            name: tor
            types:
              - deb
              - deb-src
            uris: "{{ _uri }}"
            suites: "{{ ansible_facts.distribution_release }}"
            components: main
            signed_by: "{{ _uri }}/{{ _key }}"
          register: _tor_repo

        - name: Update apt cache
          when: _tor_repo.changed
          ansible.builtin.apt:
            cache_valid_time: 1
            update_cache: true
            update_cache_retries: 1

    - name: Install/Update Tor keyring
      when: ansible_facts.distribution_release not in ('resolute')
      ansible.builtin.apt:
        name:
          - deb.torproject.org-keyring

# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1021911
- name: Allow low port for Tor apt
  when: tor_port < 1024
  vars:
    _exe: "{{ (tor_bridge_distribution | length > 0) | ternary('/usr/bin/obfs4proxy', '/usr/bin/tor') }}"
  ansible.builtin.lineinfile:
    line: >-
      DPkg::Post-Invoke { "setcap cap_net_bind_service=+ep {{ _exe }}"; };
    path: /etc/apt/apt.conf.d/99-tor-lowport

- name: Install/Update Tor
  vars:
    _backports: "{{ (ansible_facts.distribution_release == 'resolute') | ternary('', '-backports') }}"
  ansible.builtin.apt:
    default_release: "{{ ansible_facts.distribution_release }}{{ _backports }}"
    name:
      - tor
  notify: Restart Tor

- name: Install/Update PT
  when: tor_bridge_distribution | length > 0
  vars:
    _backports: "{{ (ansible_facts.distribution_release == 'resolute') | ternary('', '-backports') }}"
    _package: >-
      {{ (ansible_facts.distribution_release == 'forky') | ternary('lyrebird', 'obfs4proxy') }}
  ansible.builtin.apt:
    default_release: "{{ ansible_facts.distribution_release }}{{ _backports }}"
    name:
      - "{{ _package }}"
  notify: Restart Tor
