---
# https://support.torproject.org/apt/tor-deb-repo/
- name: Repo
  vars:
    _key: A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc # gitleaks:allow
    _uri: https://deb.torproject.org/torproject.org
  block:
    - name: Repo
      when: ansible_facts.distribution_release not in ('bullseye', 'jammy')
      block:
        - name: Enable Tor repository
          ansible.builtin.deb822_repository:
            name: tor
            types:
              - deb
              - deb-src
            uris: "{{ _uri }}"
            suites: "{{ ansible_facts.distribution_release }}"
            components: main
            signed_by: "{{ _uri }}/{{ _key }}"
          register: _tor_repo

        - name: Update apt cache
          when: _tor_repo.changed
          ansible.builtin.apt:
            cache_valid_time: 1
            update_cache: true
            update_cache_retries: 1

    - name: Legacy repo
      when: ansible_facts.distribution_release in ('jammy')
      vars:
        _keyring: /usr/share/keyrings/deb.torproject.org-keyring.gpg
      block:
        - name: Enable Tor legacy repository - tools
          ansible.builtin.apt:
            name:
              - apt-transport-https
              - gnupg

        - name: Enable Tor legacy repository - gpg key
          ansible.builtin.shell:
            cmd: >-
              curl -q {{ _uri }}/{{ _key }} -o - |
                gpg --dearmor >"{{ _keyring }}"
            creates: "{{ _keyring }}"

        - name: Enable Tor legacy repository
          ansible.builtin.apt_repository:
            filename: tor
            repo: >-
              {{ item }} [signed-by={{ _keyring }}] {{ _uri }} {{ ansible_facts.distribution_release }} main
            update_cache_retries: 1
          loop:
            - deb
            - deb-src

    - name: Install/Update Tor keyring
      when: ansible_facts.distribution_release not in ('bullseye')
      ansible.builtin.apt:
        name:
          - deb.torproject.org-keyring

# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1021911
- name: Allow low port for Tor apt
  when: tor_port < 1024
  vars:
    _exe: "{{ (tor_bridge_distribution | length > 0) | ternary('/usr/bin/obfs4proxy', '/usr/bin/tor') }}"
  ansible.builtin.lineinfile:
    line: >-
      DPkg::Post-Invoke { "setcap cap_net_bind_service=+ep {{ _exe }}"; };
    path: /etc/apt/apt.conf.d/99-tor-lowport

- name: Install/Update Tor
  ansible.builtin.apt:
    name:
      - tor
      - tor-geoipdb
  notify: Restart Tor

- name: Install/Update PT
  when: tor_bridge_distribution | length > 0
  ansible.builtin.apt:
    name:
      - obfs4proxy
  notify: Restart Tor
