---
- name: Get watchdog script
  throttle: 16
  retries: 1
  ansible.builtin.get_url:
    url: "{{ torutils_path }}/watchdog.sh"
    dest: /root/
  notify: Restart watchdog

- name: Cron job for watchdog
  ansible.builtin.cron:
    name: watchdog
    special_time: reboot
    job: >-
      nice /root/watchdog.sh {{ tor_watchdog_intervall }}
  notify: Restart watchdog

- name: Get watchdog.sh pid if any
  changed_when: _watchdog.pids | default([]) | length == 0
  community.general.pids:
    name: watchdog.sh
  register: _watchdog
  notify: Restart watchdog
