---
- name: Get watchdog script
  throttle: 16
  retries: 1
  ansible.builtin.get_url:
    url: "{{ torutils_path }}/watchdog.sh"
    dest: /root/

- name: Cron job for watchdog
  ansible.builtin.cron:
    name: watchdog
    minute: "*/15"
    job: >-
      nice /root/watchdog.sh 13 5
