---
- name: Get watchdog script
  throttle: 16
  retries: 1
  ansible.builtin.get_url:
    url: "{{ torutils_path }}/watchdog.sh"
    dest: /root/
  register: _download_watchdog

- name: Cron job for watchdog
  ansible.builtin.cron:
    name: watchdog
    special_time: reboot
    job: >-
      nice /root/watchdog.sh

- name: Get watchdog.sh pid if any
  community.general.pids:
    name: watchdog.sh
  register: _watchdog_pids_running

- name: Ensure watchdog.sh is running
  when: _download_watchdog.changed or _watchdog_pids_running.pids | length == 0
  changed_when: true
  ansible.builtin.shell:
    cmd: |-
      set -euf

      if [[ -n "{{ _watchdog_pids_running.pids | first }}" ]]; then
        kill {{ _watchdog_pids_running.pids | first }}
      fi

      echo 'nice /root/watchdog.sh &' | at now
